### ISSUE TITLE
SearchAnime method loading duplicates of first page

### ISSUE THREAD

**Issue by JaoHundred** [Ervie/jikan.net#12]
I was trying to list Animes using the fourth overload for SearchAnime, it loads fine for the first page, but it does not seems working after this. Maybe MAL changed the endpoint?

Steps to reproduce:

- Use the fourth overload, SearchAnime(string query, int page, AnimeSearchConfig config)
- From my experience, it doesnt matter if the query was empty or not
- You can use any config type, I was using AnimeSearchSortable.Title or GenreSearch.Action
- Request the first page, notice it loads as expected, after this try loading other pages, it will return the same 50 first page items

**Comment by Ervie** [comment]
Hello! Thanks for notification, it is indeed linked to some changes on MAL side. It is two separate things:

- Advanced search now **always** returns only one page. You can go on MAL and try to use advanced anime/manga search in any combination (series, rating, score, genre etc.) - what you choose does not matter, if you're still using advanced search.
- For basic search, paging changed a bit - this will require fix building an url. No matter wich page you choose, it might return same records.

For second issue I will apply a fix tomorrow and will release a new version. For former, probably I will have to remove two methods:
- SearchAnime(string query, int page, AnimeSearchConfig config)
- SearchManga(string query, int page, MangaSearchConfig config)

Because they serve no purpose after MAL changes...

**Comment by seanbreckenridge** [comment]
fyi, we've been discussing this in the #jikan-api channel in the discord

**Comment by Ervie** [comment]
Ok, will look into the thread

**Comment by Ervie** [comment]
Ok, it turned out that advanced search support pagination, but only _without_ search phrase... Weird choice by MAL. Beside fixing pagination for basic search, I removed afromentioned two methods, but added four new:

- `SearchAnime(AnimeSearchConfig searchConfig`
- `SearchAnime(AnimeSearchConfig searchConfig, int page)`
- `SearchManga(MangaSearchConfig searchConfig)`
- `SearchManga(MangaSearchConfig searchConfig, int page)`

All of them are basically advanced search, but without search phrase. Removed methods might come back in the future, but MAL have to return pagination to search phrase with advanced filters 🤷‍♂️ 
Changes are implemented in the version 1.3.3, should be visible soon on the nuget. I added information in the Readme and changelog, wiki will be updated later.

**Comment by JaoHundred** [comment]
I've checked out the discussion in Discord, really odd choices from MAL. Let's hope it's temporary. Anyway, thanks for the new version!

**Comment by seanbreckenridge** [comment]
Was reported to the MAL team and they're looking into it; seems to be a bug.

**Comment by Ervie** [comment]
For now I will be closing this issue, when the MAL fix we can return to this topic
