### ISSUE TITLE
SearchAnime results in bad request

### ISSUE THREAD

**Issue by RexfelisLOC** [Ervie/jikan.net#20]
_jikan.SearchAnime("one piece", 0) results in the following exception message:

"GET request failed. Status code: BadRequest Inner message: System.Net.Http.StreamContent"

**Comment by Ervie** [comment]
Paging starts from 1, as in the MAL - the first page return first 50 results, the second page from 51 to 100. Please refer to https://github.com/Ervie/jikan.net/wiki/SearchAnime - passing 0 or negative number will result in creation of incorrect endpoint for REST API.

I will probably implement some validation for pre-checking passed parameters and return more descriptive exception messages. For now, just passing 1 instead of 0 should work.

**Comment by RexfelisLOC** [comment]
Ah I missed that, thank you.
