### ISSUE TITLE
GetAnimeCharactersStaff(MalId) always returns null

### ISSUE THREAD

**Issue by SubZero0** [Ervie/jikan.net#3]
It started behaving like this since yesterday.
I'm sure the provided ID is valid (as being an anime) and there's also characters & staff listed at the MAL page. This same ID used to work a few days ago.
Tried with 2 different machines.

**Comment by SubZero0** [comment]
I think it was something on the API. I won't suppress exceptions anymore.

**Comment by Ervie** [comment]
Yes, if the returned value is null and you are sure that provided Id is correct, it's worth a try to not surpress warnings. If you receive parsing exception or incorrect endpoint exception, then it's library fault. But sometimes the problem lies with request to API - most of time it should return HttpStatusCode.

Maybe I should add some FAQ/troubleshoting section ReadMe/wiki.

**Comment by flashkid10** [comment]
I've been using this in case it returns null
`
      JikanDotNet.Manga Mang = null;
      while (Mang == null) Mang = await J.GetManga((x as MangaListEntry).MalId);
`
